### ISSUE TITLE
Popover arrow is overlapping on selected item in all directions other than Up direction. Please find the following attached files for reference.

### ISSUE THREAD

**Issue by abhikpo** [soberman/ARSPopover#2] opened 2015-09-30 14:04 UTC
![downdirection](https://cloud.githubusercontent.com/assets/8362388/10195199/0c08d5c2-67aa-11e5-8168-56b1242a6bb0.png)
![leftdirection](https://cloud.githubusercontent.com/assets/8362388/10195201/0c5802e6-67aa-11e5-8491-a41c10bec25d.png)
![rightdirection](https://cloud.githubusercontent.com/assets/8362388/10195202/0c5c801e-67aa-11e5-8ca1-6bbd98dde589.png)
![updirection](https://cloud.githubusercontent.com/assets/8362388/10195200/0c572f1a-67aa-11e5-96dd-b4d7b2ad8f42.png)

**Comment by soberman** [comment] 2015-10-03 19:02
Hi. You have to use `sourceRect` property to state the dimensions of you source view, in order for the popup's pin button to position itself properly.
For example, here is how you could put pin button **above** the button (in case not helping - move a button a little bit down to have some real-estate for the popover):

```
CGRectMake(CGRectGetMidX(self.button.bounds), 0, 0, CGRectGetHeight(self.button.bounds));
```

I am closing an issue, because this is not a bug.

**Closed as completed by soberman** 2015-10-03 19:02 UTC
